### ISSUE TITLE
i = 83 (Bailey, CO) coding

### ISSUE THREAD

**Issue by McCartneyAC** [washingtonpost/data-school-shootings#1]
[Bailey CO on Sept 27, 2006](https://en.wikipedia.org/wiki/Platte_Canyon_High_School_hostage_crisis)  is coded as "targeted", but should be coded as "hostage suicide"

Thanks!

**Comment by stevenrich** [comment]
we're only counting hostage suicide in cases where they do not inflict harm to others. Appreciate you looking into that and will add a note in record layout.
